services: 
  rtu:
    image: ghcr.io/patsec/ot-sim/ot-sim:main
    privileged: true 
    volumes:
      - ./rtuconfig.xml:/etc/ot-sim/config.xml 
      - /dev/gpiomem:/dev/gpiomem
    ports:
      - "127.0.0.1:23:23/tcp"
  ied:
    image: ghcr.io/patsec/ot-sim/ot-sim:main
    privileged: true 
    volumes:
      - ./iedconfig.xml:/etc/ot-sim/config.xml 
      - /dev/gpiomem:/dev/gpiomem
