services:
  rtu:
    image: ghcr.io/patsec/ot-sim/ot-sim:main
    privileged: true
    volumes:
      - ./rtuconfig.xml:/etc/ot-sim/config.xml
      - /dev/gpiomem:/dev/gpiomem
    ports:
      - "2323:23"
  ied:
    image: ghcr.io/patsec/ot-sim/ot-sim:main
    privileged: true
    volumes:
      - ./iedconfig.xml:/etc/ot-sim/config.xml
      - /dev/gpiomem:/dev/gpiomem
  vizhelper:
    image: python:3.13-rc

  
