services:
  start:
    build: .
    privileged: true
    networks:
      - ctf1
    ports:
      - "8080:8080"
      - "502:502"
  start_stop:
    build: .
    privileged: true
    networks:
      - ctf2
    ports:
      - "8081:8080"
      - "503:502"

networks:
  ctf1:
    driver: bridge
  ctf2:
    driver: bridge
