version: "3.5"

services:
  https:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "8443:8443"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mqtt-certs/server.pem:/mosquitto/config/server.pem
      - ./mqtt-certs/server.key:/mosquitto/config/server.key
      - ./mqtt-certs/ca.pem:/mosquitto/config/ca.pem
