version: "3.5"
services:
  https:
    image: jtsmart/https
    ports:
      - "3000:3000"
    links:
      - mqtt
  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "8443:8443"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mqtt-certs/server-cert.pem:/server.pem
      - .//mqtt-certs/server-key.pem:/server.key
      - ./mqtt-certs/ca-cert.pem:/ca.pem
